### ISSUE TITLE
Review port repository interface

### ISSUE THREAD

**Issue by andrzejWilde** [lootek/go-port-service#2]
Port repository interface is defined as:
```
type Port interface {
	GetAll() []domain.Port
	Insert(port domain.Port) error
	Update(id string, port domain.Port) error
}
```
Could you review methods signatures and make sure they are future-proof and reusable, please?

Hints:
- if a method uses I/O operations, it's likely sometimes these operations may fail
- how do we retrieve a reference (id) to a newly inserted entity?

**Comment by lootek** [comment]
Good point, thanks for this @andrzejWilde - I've added missing return values in #4
