### ISSUE TITLE
Review context usage

### ISSUE THREAD

**Issue by andrzejWilde** [lootek/go-port-service#3]
Usually in Golang applications context is propagated inside the app to allow for graceful shutdown. Could you review your implementation for context usage and make sure that context is properly propagated and used, please?

**Comment by lootek** [comment]
Thank you, @andrzejWilde - I've gone through the code and it looks like I was not passing the ctx down to the repository (which might be useful there depending on the particular storage implementation). Please see #5 for the changes.
